enum UserDefaultsKeys {
    static let themeID = "ThemeID"
    static let editorFontID = "EditorFontID"
    static let editorFontSize = "EditorFontSize"
    static let editorWordWrapEnabled = "EditorWordWrapEnabled"
    static let editorShowsInvisibleCharacters = "EditorShowsInvisibleCharacters"
    static let workspaceWindowFrame = "WorkspaceWindowFrame"
    static let openFilesSidebarWidth = "OpenFilesSidebarWidth"
    static let syntaxLanguageOverrides = "SyntaxLanguageOverrides"
    static let sessionRestorerDocumentReferences = "SessionRestorer.documentReferences"
    static let sessionRestorerActiveDocumentReference = "SessionRestorer.activeDocumentReference"
    static let sessionRestorerOpenFilePaths = "SessionRestorer.openFilePaths"
    static let sessionRestorerActiveFilePath = "SessionRestorer.activeFilePath"
    static let openFolders = "OpenFolders"
    static let openFoldersExpandedPaths = "OpenFolders.expandedPaths"
}
